kind: pipeline
name: CI

steps:
  - name: build
    image: node
    commands:
      - yarn
      - yarn build
  - name: Create Tag
    image: docker:git
    commands:
      - git tag $(git rev-parse HEAD)
      - git push origin --tags
  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files: dist/*
    title: Discord CSS
    when:
      event: tag
