kind: pipeline
name: CI

steps:
  - name: build
    image: node
    commands:
      - yarn
      - yarn build
    when:
      event: tag
  - name: Create Tag
    image: docker:git
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - git tag ${DRONE_BUILD_NUMBER}
      - git remote set-url origin https://pikokr:$(echo $GITHUB_TOKEN)@github.com/pikokr/discord.css.git
      - git push origin --tags
    when:
      event: push
      branch: master
  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files: dist/*
    title: Discord CSS
    when:
      event: tag
