kind: pipeline
name: CI

steps:
  - name: build
    image: node
    commands:
      - yarn
      - yarn build
  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files: dist/*
    title: Discord CSS