kind: pipeline
name: CI

steps:
  - name: Create Tag
    image: docker:git
    commands:
      - git tag ${DRONE_BUILD_NUMBER}
      - git remote set-url origin https://pikokr:repo-token@github.com/pikokr/discord.css.git
      - git push origin --tags
    when:
      event: push
      branch: master
  - name: build
      image: node
      commands:
        - yarn
        - yarn build
      when:
        event: tag
  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files: dist/*
    title: Discord CSS
    when:
      event: tag
